### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by rhodesie** [joeblau/WatchSpringboard#1]
Heya,

I came across this as I was looking to do something similar but I can't get this working under XCode 6.3 / Swift 1.2. I get numerous errors which I can't seem to get around. Are you looking to update this to the latest version of Swift any time soon?

Regards,

Paul

**Comment by joeblau** [comment]
Paul,

I wasn't looking at updating this.  I haven't touched this project in so long, but I don't think it would be that hard to update.

**Comment by rhodesie** [comment]
Heya, 

The errors I get are apparently fixed up after XCode 8.3 beta 3, sorry about that... kinda new to developing for iOS and Swift
