### ISSUE TITLE
Initialisations do not work 

### ISSUE THREAD

**Issue by ArthurU** [joeblau/WatchSpringboard#2]
Hi, sorry to keep pestering about updated versions of this, but do you know how to fix these override init() and super.init() errors. I also get the following error: 

Method 'setBounds' with Objective-C selector 'setBounds:' conflicts with setter for 'bounds' from superclass 'UIView' with the same Objective-C selector

Thanks.

**Comment by joeblau** [comment]
Yeah, there have been a lot of changes to Swift, but I haven't migrated this project.  I'm waiting for Swift 2.0 to come out and then I'll update it.

**Comment by ArthurU** [comment]
Ah ok. Hope to download it soon.
